name: polyfence_example
description: Example app for Polyfence plugin
publish_to: 'none'
version: 0.11.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  polyfence:
    path: ../
  cupertino_icons: ^1.0.2
  lucide_icons: ^0.257.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  battery_plus: ^4.0.2
  connectivity_plus: ^5.0.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
